  environment: development
  chdir: /home/username/bootcamp
  address: 127.0.0.1
  user: username
  group: username
  port: 4567
  pid: /home/username/bootcamp/thin.pid
  rackup: /home/username/bootcamp/config.ru
  log: /home/username/bootcamp/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true
